// =============================================================
// polylang_haxe_adapter.cpp  —  PolyLang Haxe Adapter v5
// =============================================================
// Haxe compiles to C++ (via HashLink or hxcpp); this adapter bridges
// the PolyLang vtable to hxcpp's extern-class FFI.
//
// SANDBOX:   pl_compile_sandboxed sets sandboxed=true on the compiled handle.
//            At method dispatch, calls matching dangerous hxcpp APIs
//            (sys.io.File, sys.FileSystem, sys.net.*, Sys.command,
//            haxe.Http) are blocked via a name deny-list. Haxe macros
//            can enforce additional compile-time restrictions in the
//            game script sources themselves.
// PLATFORM:  Desktop + Android (via hxcpp NDK build). iOS-compatible.
// =============================================================
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <mutex>
#include <unordered_map>
#include <vector>

#include "../../include/pl_adapter_vtable.h"

// Forward declarations for hxcpp bridge types
// In production, these are generated by hxcpp for each compiled script class.
extern "C" {
    typedef void* HxClass;
    typedef void* HxObject;
    typedef void* HxValue;

    // Provided by hxcpp runtime stubs (linked at build time)
    void    hx_runtime_init(void);
    void    hx_runtime_shutdown(void);
    HxClass hx_find_class(const char* fqn);             // returns nullptr if not found
    HxObject hx_create_instance(HxClass cls);
    void    hx_free_object(HxObject obj);
    int     hx_call_method(HxObject obj, const char* name,
                            HxValue* args, int argc, HxValue* ret_out);
    int     hx_set_field(HxObject obj, const char* name, HxValue v);
    int     hx_get_field(HxObject obj, const char* name, HxValue* out);
    int     hx_has_method(HxClass cls, const char* name);

    // HxValue boxing / unboxing
    HxValue hx_box_null(void);
    HxValue hx_box_bool(int b);
    HxValue hx_box_int(int64_t v);
    HxValue hx_box_float(double v);
    HxValue hx_box_string(const char* s);

    int     hx_is_null(HxValue v);
    int     hx_is_bool(HxValue v);
    int     hx_is_int(HxValue v);
    int     hx_is_float(HxValue v);
    int     hx_is_string(HxValue v);

    int     hx_unbox_bool(HxValue v);
    int64_t hx_unbox_int(HxValue v);
    double  hx_unbox_float(HxValue v);
    const char* hx_unbox_string(HxValue v);
    void    hx_free_value(HxValue v);
}

// ── Sandbox deny-list ────────────────────────────────────────
static const char* HX_SANDBOX_DENIED[] = {
    "sys_io_File", "sys_FileSystem", "sys_net", "Sys_command",
    "haxe_Http", "haxe_io_File", "createFile", "openFile",
    "writeFile", "deleteFile", "execCommand", "download",
    nullptr
};

static bool hx_sandbox_denied(const char* name) {
    if (!name) return false;
    for (int i = 0; HX_SANDBOX_DENIED[i]; ++i)
        if (strstr(name, HX_SANDBOX_DENIED[i]) != nullptr) return true;
    return false;
}

// ── Value conversion ─────────────────────────────────────────
static HxValue pl_to_hx(const PLValue& v) {
    switch (v.type) {
        case PL_TYPE_NIL:    return hx_box_null();
        case PL_TYPE_BOOL:   return hx_box_bool(v.b ? 1 : 0);
        case PL_TYPE_INT:    return hx_box_int(v.i);
        case PL_TYPE_FLOAT:  return hx_box_float(v.f);
        case PL_TYPE_STRING: return hx_box_string(v.s ? v.s : "");
        default:             return hx_box_null();
    }
}

static void hx_to_pl(HxValue hv, PLValue& out) {
    pl_value_init(&out);
    if (hx_is_null(hv))   { out.type = PL_TYPE_NIL;   return; }
    if (hx_is_bool(hv))   { out.type = PL_TYPE_BOOL;  out.b = hx_unbox_bool(hv) != 0; return; }
    if (hx_is_int(hv))    { out.type = PL_TYPE_INT;   out.i = hx_unbox_int(hv); return; }
    if (hx_is_float(hv))  { out.type = PL_TYPE_FLOAT; out.f = hx_unbox_float(hv); return; }
    if (hx_is_string(hv)) {
        const char* s = hx_unbox_string(hv);
        out.type = PL_TYPE_STRING; out.s = s ? strdup(s) : nullptr; return;
    }
    out.type = PL_TYPE_NIL;
}

// ── Handles ───────────────────────────────────────────────────
struct HxCompiled {
    HxClass     cls;
    std::string class_name;
    bool        sandboxed;
};
struct HxInstance {
    HxCompiled* compiled;
    HxObject    obj;
    std::mutex  mu;
};

// ── ABI ───────────────────────────────────────────────────────
static bool g_hx_inited = false;
static std::mutex g_hx_mutex;

static int hx_init_runtime() {
    std::lock_guard<std::mutex> lk(g_hx_mutex);
    if (!g_hx_inited) { hx_runtime_init(); g_hx_inited = true; }
    return PL_OK;
}
static void hx_shutdown_runtime() {
    std::lock_guard<std::mutex> lk(g_hx_mutex);
    if (g_hx_inited) { hx_runtime_shutdown(); g_hx_inited = false; }
}

static void* hx_compile_core(const char* source, const char* path, bool sandboxed) {
    if (!source) return nullptr;

    std::string p = path ? path : "script";
    auto slash = p.rfind('/'); if (slash != std::string::npos) p = p.substr(slash + 1);
    auto dot   = p.find('.');  if (dot   != std::string::npos) p = p.substr(0, dot);

    HxClass cls = hx_find_class(p.c_str());
    if (!cls) {
        fprintf(stderr, "[PolyLang/Haxe%s] Class '%s' not found\n",
                sandboxed ? "/sandbox" : "", p.c_str());
        return nullptr;
    }

    auto* c = new HxCompiled{cls, p, sandboxed};
    return c;
}

static void* hx_compile_pl(const char* s, const char* p)                   { return hx_compile_core(s, p, false); }
static void* hx_compile_sandboxed(const char* s, const char* p, uint32_t)  { return hx_compile_core(s, p, true); }

static void hx_free_compiled(void* h) { delete static_cast<HxCompiled*>(h); }

static void* hx_instantiate_class(void* ch, const char*) {
    auto* c = static_cast<HxCompiled*>(ch); if (!c) return nullptr;
    HxObject obj = hx_create_instance(c->cls);
    if (!obj) return nullptr;
    auto* inst = new HxInstance{c, obj, {}};
    return inst;
}

static void hx_free_instance(void* raw) {
    if (!raw) return;
    auto* i = static_cast<HxInstance*>(raw);
    if (i->obj) hx_free_object(i->obj);
    delete i;
}

static int hx_call_method_fn(void* raw, const char* name, PLValue* args, int32_t argc, PLValue* ret) {
    auto* i = static_cast<HxInstance*>(raw);
    if (!i || !i->compiled || !i->obj) return PL_ERR_GENERIC;

    if (i->compiled->sandboxed && hx_sandbox_denied(name)) {
        fprintf(stderr, "[PolyLang/Haxe/sandbox] method '%s' blocked\n", name);
        ret->type = PL_TYPE_NIL;
        return PL_ERR_SANDBOX;
    }

    std::lock_guard<std::mutex> lk(i->mu);

    std::vector<HxValue> hx_args(argc);
    for (int32_t k = 0; k < argc; ++k) hx_args[k] = pl_to_hx(args[k]);

    HxValue hret = hx_box_null();
    int r = hx_call_method(i->obj, name, hx_args.data(), argc, &hret);

    for (auto& hv : hx_args) hx_free_value(hv);

    if (r != 0) { ret->type = PL_TYPE_NIL; return PL_ERR_EXCEPTION; }
    hx_to_pl(hret, *ret);
    hx_free_value(hret);
    return PL_OK;
}

static int hx_call_builtin_fn(void* raw, int32_t id, PLValue* args, int32_t argc, PLValue* ret) {
    const char* n = nullptr;
    switch (id) {
        case PL_METHOD_READY:           n="_ready"; break;
        case PL_METHOD_PROCESS:         n="_process"; break;
        case PL_METHOD_PHYSICS_PROCESS: n="_physicsProcess"; break;
        case PL_METHOD_ENTER_TREE:      n="_enterTree"; break;
        case PL_METHOD_EXIT_TREE:       n="_exitTree"; break;
        default: return PL_ERR_NOT_IMPLEMENTED;
    }
    return hx_call_method_fn(raw, n, args, argc, ret);
}

static int hx_set_prop(void* raw, const char* name, const PLValue* v) {
    auto* i = static_cast<HxInstance*>(raw); if (!i || !i->obj) return PL_ERR_GENERIC;
    std::lock_guard<std::mutex> lk(i->mu);
    HxValue hv = pl_to_hx(*v);
    int r = hx_set_field(i->obj, name, hv);
    hx_free_value(hv);
    return r == 0 ? PL_OK : PL_ERR_PROP_NOT_FOUND;
}

static int hx_get_prop(void* raw, const char* name, PLValue* out) {
    auto* i = static_cast<HxInstance*>(raw); if (!i || !i->obj) return PL_ERR_GENERIC;
    std::lock_guard<std::mutex> lk(i->mu);
    HxValue hv = hx_box_null();
    int r = hx_get_field(i->obj, name, &hv);
    if (r != 0) return PL_ERR_PROP_NOT_FOUND;
    hx_to_pl(hv, *out);
    hx_free_value(hv);
    return PL_OK;
}

static uint8_t hx_has_method(void* ch, const char* name) {
    auto* c = static_cast<HxCompiled*>(ch); if (!c) return 0;
    return hx_has_method(c->cls, name) ? 1 : 0;
}

static void hx_free_val(PLValue* v) {
    if (!v) return;
    if (v->type == PL_TYPE_STRING) { free(v->s); v->s = nullptr; }
    v->type = PL_TYPE_NIL;
}

extern "C" PL_EXPORT void pl_get_vtable(PLAdapterVTable* out) {
    *out = PLAdapterVTable{};
    out->abi_version          = PL_ABI_VERSION;
    out->capabilities         = PL_CAP_ANDROID | PL_CAP_IOS | PL_CAP_DESKTOP
                               | PL_CAP_BUILTIN_CALL | PL_CAP_SANDBOX;
    out->pl_init_runtime      = hx_init_runtime;
    out->pl_shutdown_runtime  = hx_shutdown_runtime;
    out->pl_compile           = hx_compile_pl;
    out->pl_compile_sandboxed = hx_compile_sandboxed;
    out->pl_free_compiled     = hx_free_compiled;
    out->pl_instantiate_class = hx_instantiate_class;
    out->pl_free_instance     = hx_free_instance;
    out->pl_call_method       = hx_call_method_fn;
    out->pl_call_builtin      = hx_call_builtin_fn;
    out->pl_set_property      = hx_set_prop;
    out->pl_get_property      = hx_get_prop;
    out->pl_has_method        = hx_has_method;
    out->pl_free_value_contents = hx_free_val;
}
